# Configuration for data processing for the FULL model

# Path to the tokenizer configuration file
# Relative to where train_flow_model.py is run from, OR use absolute Colab paths
# If train_flow_model.py is run from /content/beefai_project/scripts/
tokenizer_path: "../beefai/flow_model/flow_tokenizer_config_v2.json" # Relative path

# Tokenized data paths (input for FlowDataset)
# Relative to where train_flow_model.py is run from, OR use absolute Colab paths
# If train_flow_model.py is run from /content/beefai_project/scripts/
train_data_path: "../data/tokenized_full/train_full.pt"
val_data_path: "../data/tokenized_full/val_full.pt"

# Checkpoint directory
# This can be a local Colab path (temporary) or a Google Drive path
checkpoint_dir: "/content/beefai_project/colab_checkpoints/flow_model_full/" # Example local Colab path

# --- Inputs for 05b_tokenize_data_full.py (Not used by train_flow_model.py directly) ---
processed_data_source_dir: "../data/processed_for_transformer/" # Example relative

# --- Parameters for 05b_tokenize_data_full.py (Not used by train_flow_model.py) ---
max_songs_for_full: -1
val_split_ratio_for_full: 0.1

# Audio processing parameters (reference, not used by train_flow_model.py)
sample_rate: 44100
n_fft: 2048
hop_length: 512
win_length: 2048
n_mels: 128
fmin: 0
fmax: 16000