# Configuration for data processing for the LITE model

# Paths for 05a_tokenize_data_lite.py and train_lite_flow_model.py
# These are relative to the project root.

# Path to the tokenizer configuration file.
# This file is created/used by preprocess_dataset.py and then read by 05a_tokenize_data_lite.py and train_lite_flow_model.py
tokenizer_path: "beefai/flow_model/flow_tokenizer_config_v2.json"

# --- Inputs for 05a_tokenize_data_lite.py ---
# This directory contains the cached outputs (beat_features_cache, flow_data_cache)
# from the main `scripts/preprocess_dataset.py` script.
processed_data_source_dir: "data/processed_for_transformer/" # IMPORTANT: Update if your processed data from preprocess_dataset.py is elsewhere.

# --- Outputs for 05a_tokenize_data_lite.py ---
# These .pt files will contain tokenized data ready for FlowDataset.
# These paths are also used as inputs by train_lite_flow_model.py.
tokenized_data_output_dir: "data/tokenized_lite/" # Base directory for lite tokenized data
train_data_path: "data/tokenized_lite/train_lite.pt"
val_data_path: "data/tokenized_lite/val_lite.pt" # Optional, will be created if VAL_SPLIT_RATIO > 0

# --- Parameters for 05a_tokenize_data_lite.py ---
max_songs_for_lite: 10 # Number of songs to select from processed_data_source_dir for the lite dataset
val_split_ratio_for_lite: 0.2 # Proportion of selected songs to use for validation

# --- Checkpoint directory for train_lite_flow_model.py ---
checkpoint_dir: "data/checkpoints/flow_model_lite/"

# --- Parameters below are more for preprocess_dataset.py (or if data_config_lite were used there directly) ---
# Kept for reference, but `preprocess_dataset.py` currently uses command-line args or its internal defaults
# for its direct input/output paths.
# raw_data_dir: "data/instrumentals/" # This would be for preprocess_dataset
# processed_data_dir: "data/processed_for_transformer/" # This is where preprocess_dataset saves
# phoneme_dict_path: "beefai/data_processing/cmudict-0.7b.txt"

# Audio processing parameters (used by feature extractors called by preprocess_dataset.py)
sample_rate: 44100 # Ensure this matches BeatFeatureExtractor and FlowDataExtractor instantiation if they don't read this config
n_fft: 2048 # Example, BFE/FDE might have their own defaults
hop_length: 512
win_length: 2048
n_mels: 128 # Example
fmin: 0
fmax: 16000

# Max sequence length for the model's input sequences (used by FlowDataset in train_lite_flow_model.py)
# This should ideally match model_config_lite.yaml's block_size or be related.
# For FlowDataset, the block_size from model_config is passed directly.
# max_sequence_length_for_dataset_slicing: 256