block_size: 128      # Max sequence length (reduced)
n_layer: 3           # Number of Transformer layers (reduced)
n_head: 4            # Number of attention heads (reduced)
n_embd: 256          # Embedding dimension (reduced, must be div by n_head)
max_segment_types: 16 # Max number of segments (e.g., beat_features, flow_line_1, flow_line_2...)
                     # Increased to be safer, should accommodate tokenizer output for typical short songs.
max_intra_line_positions: 32 # Max positions within a segment component
                             # Increased to be safer.
dropout: 0.1
bias: True